### PR TITLE
Tie-in and tie-off

### LINKED ISSUE #28: Tie-in and tie-off stitches
For home embroidery machines, we can kind of get away with no tie-in or tie-off stitches.  But for commercial embroidery with trimming and multiple needles, tie stitches are a must.  It'd be cool if the user could just check a box for tie-in and another for tie-off to have the tie stitches generated automatically.  Another option would be to automatically tie off after a TRIM and tie-in on the next object.

@wwderw How would you expect tie-in and tie-off to be generated by the software?  I'm thinking it could generate the stitch plan for the object first, then add tie-in or tie-off stitches after.  For tie-off, it could back-track along the stitch plan and then forward again.  For example, if you number the stitches for a 100-stitch object "... 97 98 99 100", then it could repeat the last couple: "... 97 98 99 100 99 98 99 100".  In fact, very early versions of the old inkscape-embroidery project did exactly this.

Another option would be to backtrack along the _direction_ of the stitch plan, but only go a set number of millimeters.  Is that preferable?

For tie-in we could just do the reverse of what we pick for tie-off.

### PR DESCRIPTION
**Pull request by lexelby**
fixes #28 

I've finally put together an implementation of tie-in and tie-off that I feel satisfied with.  I ended up needing to reorganize the code a bit because tie-in and tie-off actually need to share some code with the running-stitch code.

Based on the discussion in #28, here's what I came up with.  When ink/stitch wants to tie off the thread, it backtracks along the stitch path 0.3mm, then another 0.3mm, then comes forward 0.3mm, and finally back to where it started, for a total of 4 extra stitches in most cases.  It will add a stitch as necessary to avoid rounding a corner in this process.  I could easily code it to go back 0.9mm, or go back in different increments, if my current choices don't look right.

For tie-in, it does the same process in reverse.

Ink/stitch will add tie stitches in the following situations:

* at the start of the design
* before and after a jump stitch
* before and after a trim
* before and after a color change

Jump stitches are where things get interesting.  Ink/stitch has always inserted JUMP instructions between embroidery elements.  The definition of an element is probably surprising: it considers underlay to be a separate element from top stitching, even for the same satin or fill.

It's not particularly useful to tie off after doing a center underlay for a satin and before doing the satin stitching.  It's a waste of stitches and of course there's the risk of leaving an unsightly knot or even breaking the needle if too many stitches pile up.

While looking into this, I finally understood a feature that has been in this project since well before I joined, the "collapse length".  You can see that in the extension settings when you do Embroider.  When ink/stitch is about to add a JUMP instruction between two embroidery elements, it checks whether the distance of the jump is less than the collapse length.  If so, it doesn't encode a JUMP and just treats it as a normal stitch.

With that understanding, I've changed the default "collapse length" to 3mm.  I actually think it might be a good idea to remove this setting entirely in favor of hard-coding a value, perhaps even longer like 5mm or 8mm.  I don't see much value in giving the user the ability to change this.

Another argument in favor of removing the collapse length option is that the Params and Simulate extensions don't even allow you to specify this value.  They just use the default.

cc @wwderw

### CODE REVIEW

**Comment by lexelby** [comment]
@wwderw When you have a chance, could you please check this version out and see if the tie in/off looks right?

**Comment by lexelby** [comment]
https://github.com/lexelby/inkstitch/releases/tag/dev-build-tie-off

**Comment by wwderw** [comment]
I'll create some files tonight and I'll run them tomorrow.

**Comment by lexelby** [comment]
Thanks!  Can you post your test file?  Both the SVG and DST would help.

**Comment by wwderw** [comment]
[TieInTieOff.zip](https://github.com/lexelby/inkstitch/files/1764078/TieInTieOff.zip)

I've included the CSV and the DST (didn't save the SVG).

Based on what I could tell from the CSV, it looks like it is doing everything that it should be.  I was going off visual/auditory cues on the machine to make sure.  It is very possible that I could have missed it.

**Comment by lexelby** [comment]
Ah, wonderful!  It's also possible that I haven't added enough stitches or that they're not far enough apart.  Is there any way for you to tell if the ties are doing their job?

**Comment by wwderw** [comment]
> Is there any way for you to tell if the ties are doing their job?

They passed my "tweezer" test.

**Comment by lexelby** [comment]
Excellent, thanks!

**Pull request merged**
