### PR TITLE
fix empty subpath

### LINKED ISSUE #183: Converting AI file to SVG causes Crash
Traceback (most recent call last):
  File "inkstitch.py", line 20, in <module>
    if script_name.endswith('.py'):
  File "inkscape-0.92.2\share\extensions\inkex.py", line 283, in affect
  File "lib\extensions\embroider.py", line 84, in effect
  File "lib\extensions\base.py", line 196, in elements_to_patches
  File "lib\elements\element.py", line 254, in embroider
  File "lib\elements\stroke.py", line 157, in to_patches
  File "lib\elements\stroke.py", line 142, in stroke_points
IndexError: list index out of range

Inkscape version 0.92.3 (2405546, 2018-03-11)
Inkstitch 1.8.1 win32

I have a logo that is in AI format. I have imported it into Inkscape, applied Fill and Stroke to everything. It is a combination of fonts and geometric shapes. The geometric shapes work fine, the fonts do not work.  I'm not well versed in Inkscape to know what the issue is, but I thought erroring out and throwing a stack trace was an issue. I'm sure its something I'm doing, or something wrong with the file, but I can't figure it out.

### PR DESCRIPTION
**Pull request by lexelby**
fixes #183 

This fixes a crash when a subpath contains only a single point.  I also took advantage of the opportunity to retrofit the code to use a new library routine I wrote previously.  I think this is the last step in the major code reworking I've been doing over the past few months.

### CODE REVIEW

**Comment by lexelby** [comment]
@sctn4elk Can you give this version a test?  I think it should fix your problem :D 

https://github.com/lexelby/inkstitch/releases/tag/dev-build-lexelby-fix-empty-subpath

**Comment by X3msnake** [comment]
It's Working 

image

This patch also solves the error with the overlapping unwelded endpoints beware that unwelded points show different when you stitch them, should we warn the user?

Found another bug with @sctn4elk file. If you ctl+select inside the S letter of the group and try to embroider inkscape crashes without error.

could not reproduce this on a built from scratch file with groups so it's probably not a bug

**Comment by sctn4elk** [comment]
@lexelby Yes, that version seems to work for the original file with all of the components together.

**Comment by lexelby** [comment]
Thanks, glad it's working for you!

@x3msnake Inkscape will crash if an extension outputs invalid xml.  I'll see if I can reproduce this on my machine later today.  It's easier to see what's happening in a case like this on Linux because I can run inkscape from the command line.

**Comment by lexelby** [comment]
> This patch also solves the error with the overlapping unwelded endpoints beware that unwelded points show different when you stitch them, should we warn the user?

@X3msnake I don't understand.  Does this version change how unwelded points are stitched out?  I can't seem to spot the difference.  Could you post a screenshot?

**Comment by sctn4elk** [comment]
This may just be because I am not versed in Inkscape, but when I add a stroke width increase it seems Inkstitch increases the zig-zag outline and leaves the original width in the background. I am simply trying to increase the font width as our embroidery machine doesn't like the narrow font.

Original
inkstitch1

Stroke width increased by .5mm
inkstitch3

**Comment by X3msnake** [comment]
@sctn4elk You are going at it the wrong way

You need to do a offset if you want your font to be fatter. Changing stroke width will make a zigzag fixed width satin column with the size of your stroke width.

But either way the propper way to do this is not using neither fill nor fixed width satin columns.

You will need to work each shape as manual satins and use rungs to define the direction of the stitch.

Check this timelapse on a small font logo i did
https://www.youtube.com/watch?v=IzS4XQQS14Q

**Comment by lexelby** [comment]
@sctn4elk What @X3msnake said, plus:

Your shapes have both a fill _and_ a stroke.  The fill means that Ink/Stitch will try to do fill stitch, that is, it will fill the shapes with rows of stitches.  For shapes that are thin like these, fill stitch really doesn't make sense, and your machine's going to choke on all the stitches crammed in a little space.

There are some example SVG files bundled with Ink/Stitch, including a few renditions of the Ink/Stitch logo.  They contain examples of text that might make it more clear how to do text.

Thanks for asking questions!  Seeing the things you're stumbling on helps us know where to improve our documentation.

**Comment by danielkschneider** [comment]
There is an error message missing. When "d" is an empty string I get an out of range error. I don't know how this can happen. I found this element in a file with lots of paths, i.e. I was able to create a stitch file with all selected elements on the screen, but not with all selected elements in the objects list.

    <path
       embroider_trim_after="True"
       embroider_zigzag_underlay="False"
       embroider_contour_underlay="False"
       embroider_center_walk_underlay="False"
       embroider_satin_column="False"
       embroider_repeats="2"
       id="path5478"
       style="fill:none;stroke:#000000;stroke-width:0.28098291"
       d=""
       inkscape:connector-curvature="0" />

Traceback (most recent call last):
  File "inkstitch.py", line 20, in <module>
    if script_name.endswith('.py'):
  File "inkscape-0.92.2/share/extensions/inkex.py", line 283, in affect
  File "lib/extensions/embroider.py", line 83, in effect
  File "lib/extensions/base.py", line 198, in elements_to_patches
  File "lib/elements/element.py", line 264, in embroider
  File "lib/elements/stroke.py", line 142, in to_patches
  File "lib/elements/stroke.py", line 46, in paths
  File "site-packages/backports/functools_lru_cache.py", line 113, in wrapper
  File "lib/elements/element.py", line 206, in parse_path
  File "lib/elements/element.py", line 202, in path
  File "inkscape-0.92.2/share/extensions/cubicsuperpath.py", line 163, in parsePath
  File "inkscape-0.92.2/share/extensions/cubicsuperpath.py", line 150, in CubicSuperPath
IndexError: list index out of range

**Comment by lexelby** [comment]
Well that sure is weird.  Could you please file this as a separate bug?  I think the best thing to do here is add an error message.

**Pull request merged**
