### PR TITLE
Monogram example with "knockdown" stitches

### PR DESCRIPTION
**Pull request by wwderw**

### CODE REVIEW

**Comment by lexelby** [comment]
So cool!  Thanks for adding this.  I especially like the sharp corners on the lower wing parts.  It's useful to see how to do that with the overlapping satin.

It looks like the stitch plan is showing and the instructions aren't.  Is that intentional?

Also, the arch that goes behind the antennae -- is that going to hold together without a running stitch under it?  Does a satin just hold itself together automatically?

**Comment by wwderw** [comment]
> It looks like the stitch plan is showing and the instructions aren't. Is that intentional?

I had just done a exporting of a DST version and I forgot to delete the stitch plan and turn everything else back on.

>Also, the arch that goes behind the antennae -- is that going to hold together without a running stitch under it? Does a satin just hold itself together automatically?

Thanks for the catch.  All those other satin stitches had travel run stitches to tack them down.  I got use to that when I made it around to that section.

I'll delete the old version on there and but in a new one.

**Comment by wwderw** [comment]
I thought I would post this here, as I'm also including this example in the same PR.

Just an example of a simple monogram frame.

monogram example

**Comment by lexelby** [comment]
Cool!

**Pull request merged**
