### PR TITLE
additional print features

### PR DESCRIPTION
**Pull request by lexelby**
This adds the following:
  * pan and zoom support
  * saving and restoring of settings, editable fields, and pan and zoom settings
  * select your own branding icon by clicking the icon
  * button to save view settings, paper size, and icon globally
  * editable box in the operator detailed view for arbitrary notes

### CODE REVIEW

**Comment by wwderw** [comment]
> Next up, I'm going to add support for selecting an icon. I haven't decided yet whether the icon should be per-SVG or whether it should be a global setting. @wwderw what do you think?

For me, personally, I would make it global.

There may be a time or two where I would swap it, but by far I would probably stick with one icon for the majority.

Only way around that that I could think of is if it would be possible to have two buttons.  One that says "save" and that would apply globally.  And another button that says "ok" and that would override that icon just for that one instances.  The next SVG that is created, it goes back to the global setting.

Thoughts or not even worth having that extra option?

**Comment by lexelby** [comment]
I was thinking along those lines too.  I'm in the middle of coding a "Save as defaults" button at the bottom of the settings window.  It would save the paper size, view checkboxes, and the icon as global defaults.  Sound good?

**Comment by wwderw** [comment]
That sounds good to me.

**Comment by X3msnake** [comment]
Awsome :)

By the way, by icon you mean the branding logo correct?

**Comment by kaalleen** [comment]
I created a print-pdf2 branch a while ago. Didn't know you would start working on this topic so soon, so I didn't make it a pull request yet. But since this is working on the same files... maybe you could merge these two together? Changes until now are scaling and dragging the svg.

> I was thinking along those lines too. I'm in the middle of coding a "Save as defaults" button at the bottom of the settings window. It would save the paper size, view checkboxes, and the icon as global defaults. Sound good?

Sounds good for me too :)

**Comment by lexelby** [comment]
Oh!! I totally missed that.  I'll merge that into mine when I have a chance.

**Comment by kaalleen** [comment]
Sorry, my mistake. I should have said something.

**Comment by lexelby** [comment]
@kaalleen love it!  I merged in your branch and riffed on it a bit.  Now the position of the SVG updates continously as you drag it, and I used a sneaky closure trick to avoid having to store data on the element.

I also tweaked the scroll/zoom functionality, making it scale proportionally.  Before, it would "feel" like it was zooming in less the bigger you made the SVG.

**Comment by lexelby** [comment]
@kaalleen What was your thinking behind this?

```
    // Do not scale to more than 100%
    scale = (scale <= 1) ? scale : 1;
```

To me it feels like "fit" _should_ expand beyond 100% if necessary.  As a user, I found it a little weird that "fit" seemed to do nothing.  I'm especially likely to run into this since my machine has only a 4x4" hoop.

**Comment by kaalleen** [comment]
@lexelby Good you like it ... and good you made changes to it! I will test it soon.
If it feels wrong I would not complain at all, if you changed it to scale to more than 100% percent. As I cannot sit long these days, I have no recent experience using the software. If I would, I would probably run into the same problem as you do, because my machines hoop isn't bigger than yours ;)

**Comment by lexelby** [comment]
I'm sorry you're having trouble, but it's good to hear from you even with your limited available computer time!

I'm currently working on integrating scaling/dragging with my code to save and restore settings into the SVG.  Stay tuned.

**Comment by kaalleen** [comment]
I had a closer look and tested functionality. I like how you cleaned up my code. I tend to create chaos, when I am testing things out.
I somehow couldn't scale the image. Was a small error which I had build into it. So I fixed it.
Excited to see your next steps ;)

**Comment by lexelby** [comment]
Huh!  That's really weird, because it totally worked fine for me.  I wonder why?

**Comment by lexelby** [comment]
I've added save/restore functionality for the transform. Really close now!

**Comment by lexelby** [comment]
Operator notes added!

**Comment by wwderw** [comment]
On the Windows version I couldn't get anything to save (I haven't been able to test on the Linux side of things, I think I figured out where Kubuntu went work that forced me to package within the AppImage, I'll test the theory when 18.04 is releases this Thurs.).

The icon didn't change, the notes (which was just simply "test") didn't save, thread color name didn't as well.

I did every which way that I could think to save it.  Using the "save as defaults" (although I don't think that would apply to anything other then what sheets are visible and the logo icon) and closing the connection via web browser versus just closing out the tab.  I may be missing a step.

**Comment by lexelby** [comment]
Huh, interesting.  I'll give it a try on Windows when I get a chance.

**Comment by lexelby** [comment]
@wwderw I was able to reproduce the problem you had, and it turns out it wasn't Windows-specific.  It was a combination of a bug in this branch and a really weird inkscape behavior that masked it on my side so that I didn't notice it in testing.

I've pushed up a new commit that should fix it.  *You'll need to entirely restart Inkscape* after installing this new version in order for the fix to work, due to the aforementioned weird inkscape behavior.  That should only be necessary for folks that tested the buggy version of this branch though.

**Comment by wwderw** [comment]
I'll see about giving it a spin, hopefully later on tonight, if not tomorrow.

Looking forward to it.

Thanks!

**Comment by wwderw** [comment]
The notes and other test inputs did retain through a close out of both the print extension and the program and were still there after opening back up.

However, there is no toggle input for swapping out the logo to a user defined logo and dropping a logo manually using windows explorer and saving over the default logo did not yield a change either.

**Comment by lexelby** [comment]
Hmmm.  Clicking the logo didn't open up a file picker dialog?  I guess having to click it may not be a very discoverable UI...

**Comment by lexelby** [comment]
Aw, congrats on the youngster!  Don't worry about it.  I want our UI to make intuitive sense and be easy to discover.  We'll write docs, but I would love it if folks could naturally discover most of the ui features without it.

With that in mind, do you think it would help to add a note below the icon, "click to choose an icon"?

**Comment by wwderw** [comment]
I had figured that it was clickable, but then again, that could have been because I was used to the original dev version that had the box there as well.  So I don't know if that left it in my mind that it was possible or not.

I think in the docs should be fine in of itself, I think having the text click to choose icon may do away with the seamless look for those that are using this for business use.  It may be distracting for their customer.  So I would just vote in the docs.  I may try to do a tut on it as well.  Trying to find time to do one on give a little peek of manual input and general print usage (I try to base them on the latest stable version as I'm doing the video).

**Comment by lexelby** [comment]
Would it change your mind if I told you the text would only appear there in the browser, but it wouldn't show in the printout?  It's quite easy to hide stuff in the printout like that, with the way we have things set up.

**Comment by wwderw** [comment]
Oh, if it can be hidden then that wouldn't be a problem at all.  Good to go.

**Pull request merged**
