### PR TITLE
single code entry point

### LINKED ISSUE #158: combine all extensions into a single script/executable
Currently the various extensions (Embroider, Print, Params, etc) are separate python scripts (or executables in the built releases).  There's been a lot of refactoring recently with the result that the actual entry scripts for each extension don't have all that much code in them.  Each consists of a fairly simple python class (a subclass of `InkstitchExtension`) that makes use of lots of library functions and classes.

We could combine this down to a single entry point.  It would be a simple script that pulls in the correct `InkstitchExtension` subclass and runs it.

There are two big advantages to this:

1. The build process would be greatly simplified.
2. Build time would be dramatically reduced (especially on Windows)

The second is especially important because it means we won't have an incremental cost for adding more extensions.

### PR DESCRIPTION
**Pull request by lexelby**
This is an "under the hood" change that combines everything into a single executable.  This is great for all the reasons described in #158.  It also reduces the size of the windows and linux versions by 20MB each!

I took this opportunity to complete the refactoring work that I started when I implemented the original Print PDF feature.  Now the codebase is sleek and streamlined and just makes sense when you look at it.  Hopefully this will make it more accessible to any more developers that want to join in :)

Please test this pretty thoroughly.  No new features, but I had to move around a fair bit of the code and it's possible that I broke something.

fixes #158

### CODE REVIEW

**Comment by lexelby** [comment]
Wow!! Thanks to an idea originally put forward by @AkiraNorthstar, I enabled debug symbol stripping on the Linux version and that brings the size of the tarball down to 38MB!!

**Comment by wwderw** [comment]
So far, I haven't found any bugs yet.  I'm hoping to be able to give it a more thorough going over this weekend.

**Comment by lexelby** [comment]
Thanks!

**Comment by X3msnake** [comment]
Been away these last weeks but i will see if i can test it this weekend

**Comment by wwderw** [comment]
Couple of errors:

1.  Click to change icon on the pdf worksheet, goes through all the steps, but doesn't actually use the new logo.  However, drag/drop/overwrite old file with the new one does.

2.  Sometimes this works, sometimes it doesn't.  I had expanded the area to see if it was just being covered up.  The original view was flush with white box area.

preview area

**Comment by lexelby** [comment]
> Click to change icon on the pdf worksheet, goes through all the steps, but doesn't actually use the new logo. However, drag/drop/overwrite old file with the new one does.

Huh.  It seems to work fine for me.  What browser are you using?

I actually can't get drag/drop to work at all.  That doesn't surprise me, because I didn't code it to work that way.  If you have time, maybe you could record a screen video showing me what you're seeing?

> Sometimes this works, sometimes it doesn't. I had expanded the area to see if it was just being covered up. The original view was flush with white box area.

Hmmm, that looks like the simulate preview in Params, right?  What exactly goes wrong with it?  A video might help here, too.

**Comment by wwderw** [comment]
>Huh. It seems to work fine for me. What browser are you using?

FF 59.0.2 64 bit

>I actually can't get drag/drop to work at all. That doesn't surprise me, because I didn't code it to work that way.

If you have the same name as the original, overwrite the original file in the print/resources folder it works.  That's the only way that it's been stable for me.

>If you have time, maybe you could record a screen video showing me what you're seeing?


[Change Logo.zip](https://github.com/lexelby/inkstitch/files/1976210/Change.Logo.zip)

>Hmmm, that looks like the simulate preview in Params, right? What exactly goes wrong with it? A video might help here, too.

1st screenshot.  If you look, top right of the object cuts off the simulation of the object.  The crossair for the end point is off in no man's land.

preview area

Same shape object, but it does it as it should:

preview area2

It appears to be an intermittent issue.

**Comment by lexelby** [comment]
Found a bug!  Embroider would crash if you ran it on an SVG with "embroidery origin" guides set.

@wwderw I still haven't been able to reproduce that issue with the preview. :(  Is it happening on all of your designs or just a specific one?  Is it for all objects or just that one in your picture?  How often does it happen?

**Comment by lexelby** [comment]
@wwderw On the plus side, I did find and fix that icon issue on Firefox.  I think that's been a bug all along and unrelated to this branch, but I might as well fix it while I'm at it.

**Comment by wwderw** [comment]
I tried that shape several times since the 2nd time that I did it and it hasn't come back.
I wonder if I did something else that was totally random that through it off.  I dunno.

That's the frustrating thing about it.  Makes me feel like I'm off my rocker (and depending on who you talk to, they might say that is the case).

**Comment by lexelby** [comment]
Oh, I could easily believe that there's an intermittent bug here.  I think it's pretty likely that it's not related to the changes I made in this branch, so let's just keep our eyes out for this bug in the future.  Hopefully we can catch it at some point.

Other than that, I think we're ready to go with this branch?

**Comment by lexelby** [comment]
Alright, I'm gonna merge this and tag a new release.  Hopefully I didn't miss any more broken functionality :)

**Comment by X3msnake** [comment]
I've been meaning to do some logos for practice . Think I will do it tomorrow with the latest release. Maybe i'll give it a shot at a video ;)

**Pull request merged**
