### PR TITLE
replace outdated/redundant README with pointers to the website

### PR DESCRIPTION
**Pull request by lexelby**
With all the work you folks have been doing on the website, the README is now outdated, misleading, and redundant.  Here's a much shorter version with pointers into the website.  I also added a section more relevant to folks who've come to the project page on GitHub, explaining a bit about the history of Ink/Stitch and my (our?) philosophy in making it.

Let me know what you folks think.

### CODE REVIEW

**Comment by wwderw** [comment]
I think at this stage, this is a better version of the readme where it doesn't go over the nitty gritty as there are other avenues that we have for that (website, videos etc) with the operation etc of the extension.

**Comment by X3msnake** [comment]
@lexelby 

Cool, nice move :)
Very good

Just to clarify the hard work on the website site has been mainly @kaalleen she deserves most of the credit there. :)

Thanks for your dedication to the project Master K

**Comment by lexelby** [comment]
I added a "before/after" image of the Ink/Stitch logo on the right, showing the SVG version and the realistic rendering.  Hopefully that gets people interested :)

**Comment by X3msnake** [comment]
@lexelby Cooool :D nice touch

**Pull request merged**
