### PR TITLE
pyinstaller release method

### PR DESCRIPTION
**Pull request by lexelby**
pyinstaller packages up all of a python script's dependencies and builds them into standalone executables.  It can either do a directory (containing a single executable and a bunch of shared libraries) or a self-contained executable that effectively just contains a compressed version of the directory.
    
The problem is, if you have several scripts like we do, you get several large directories or standalone binaries, and there's a ton of duplication between them.  Fortunately it looks like using the directory method and just combining the directories works fine (for this project).

This PR runs the above build on any tagged commit and publishes a release in github containing the pyinstall-ified tarball.  If the tag is named like `v1.2.3` _and_ the tag is on the master branch, then the github release will be marked as "production".  Otherwise, it will be marked as a "pre-release".  This means that we can build testable tarballs of the extension in a pull request by tagging a commit.

### CODE REVIEW

**Comment by lexelby** [comment]
@wwderw Could you give this one a go? https://github.com/lexelby/inkstitch/releases/download/v1.0.5/inkstitch-v1.0.5-Linux-x86_64.tar.gz

I still haven't gotten travis-ci to build one for me, but I went ahead and built this one in an ubuntu 14.04 VM.  That should mean it will be compatible with your system's libc.

If it throws an error, could you please paste the whole thing, even if it seems the same as last time?

**Comment by wwderw** [comment]
Embroider worked.

Params came up, I was able to input what I wanted (when I got to a certain point the stitch preview came up, that's COOL!), however when I clicked "apply and quite", it didn't take affect visually in the program like Embroider does.

Simulate returned this error

`(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:28:16: 'outline-radius' is not a valid property name

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:109:23: No property named '-gtk-icon-transform'

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:240:26: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:249:32: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:261:52: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:266:65: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:278:36: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:315:38: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:340:86: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:363:62: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:398:66: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:447:166: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:472:90: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:483:114: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:488:127: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:491:8: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:493:8: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:496:8: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:499:8: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:501:8: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:504:8: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:507:8: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:510:8: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:516:8: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:521:8: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:526:8: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:531:8: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:533:8: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:535:8: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:537:8: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:540:8: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:542:10: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:555:41: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:558:49: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:561:47: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:567:36: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:570:32: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:575:40: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:580:38: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:585:33: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:588:45: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:590:27: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:592:27: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:594:36: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:597:274: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:629:90: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:639:87: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:650:87: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:661:124: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:680:124: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:685:64: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:701:24: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:704:2: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:706:4: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:708:17: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:710:4: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:712:17: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:714:4: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:716:17: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:718:4: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:721:8: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:912:84: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:921:110: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1040:88: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1054:124: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1058:25: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1079:25: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1091:25: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1102:27: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1110:27: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1127:27: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1135:25: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1143:27: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1151:25: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1153:25: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1157:25: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1161:25: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1163:25: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1167:25: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1171:25: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1175:25: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1183:25: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1191:25: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1217:139: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1257:145: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1396:30: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1685:31: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1688:33: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1693:33: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1696:33: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1699:33: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1868:7: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1871:98: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1875:23: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1880:7: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1883:98: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1887:23: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1940:7: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1943:98: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1947:23: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1952:7: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1955:98: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1959:23: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1964:25: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1968:25: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:1983:16: 'outline-radius' is not a valid property name

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:2178:64: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:2198:12: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:2290:16: 'outline-radius' is not a valid property name

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:2295:25: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:2309:34: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:2377:165: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:2386:129: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:2599:74: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:2725:35: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:2775:16: 'outline-radius' is not a valid property name

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:2812:47: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:2817:49: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:2819:49: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:2824:49: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:2826:47: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:2828:49: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:2907:22: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:2932:19: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:2939:21: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:2943:21: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:2948:21: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:2954:21: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:2958:19: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:2965:19: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:2999:16: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:3135:43: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:3173:126: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:3178:30: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:3184:38: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:3188:39: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:3243:58: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:3388:56: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:3421:60: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:3453:58: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:3472:56: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:3581:46: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:3752:211: Missing name of pseudo-class

(embroider_simulate:10733): Gtk-WARNING **: Theme parsing error: gtk.css:3784:75: Missing name of pseudo-class
Traceback (most recent call last):
  File "embroider_simulate.py", line 341, in <module>
    
  File "inkex.py", line 283, in affect
  File "embroider_simulate.py", line 325, in effect
    
  File "embroider_simulate.py", line 333, in get_stitch_file
    
AttributeError: 'NoneType' object has no attribute 'replace'
[10733] Failed to execute script embroider_simulate
`

**Comment by wwderw** [comment]
Now, why isn't the code appearing in a nice box like before?  Way too long of a response otherwise.  Is it due to the spaces?

**Comment by wwderw** [comment]
I went through the XML editor and while I didn't get a visual change of Params, I was able to see the settings and they were there and I was able to change them.  I haven't exported any files to see if changes via XML are truly applied when exporting CSV.  Try that this evening.

**Comment by lexelby** [comment]
YAY!

Embroider params was actually doing exactly what it's supposed to do.  It sets hidden XML parameters in the SVG (which is just an XML file) that change Embroider's behavior.  See my <a href="https://github.com/lexelby/inkstitch#workflow">workflow notes</a> for more of an explanation.

The "theme parsing error" messages can be safely ignored.  I'll add code to silence those.

Looks like simulate crashed for you!  That's just a bug in simulate having nothing to do with the pyinstaller packaging.  Would you be willing to share the SVG file and the CSV file that Embroider produced so I can try to reproduce the crash?

>  Now, why isn't the code appearing in a nice box like before?

Do you mean the single-file executables?  I could do that again, but pyinstaller packages all of the libraries needed for each of the extensions separately, and there's a ton of overlap.  The result is a much bigger tarball -- hundreds of megs.  It also takes several seconds for the executable to unpack behind the scenes on each run, which I found quite slow.

> Way too long of a response otherwise. Is it due to the spaces?

Not sure I follow?  Is it taking a long time for Embroider to run?

**Comment by lexelby** [comment]
Oh, I think I see what happened with Simulate.  It didn't find the CSV output from Embroider, and it the error handling logic there isn't very good.

**Comment by wwderw** [comment]
> Not sure I follow? Is it taking a long time for Embroider to run?

Oh no, I was talking about my copy and pasting the error msg so you would know what went on in this thread.  I tried to use the "code" (') in order to where it would show up in a box and not generate such a long response.  

No, the extension itself was fine.  I don't mind the little extra time to run itself with what I was trying to accomplish.

**Comment by wwderw** [comment]
I've just been playing with some shapes here and there.

I'll try to do something a little bit more complex later.  What's the best way to send stuff when I'm ready?

**Comment by lexelby** [comment]
If you're willing to post stuff publicly, you can just attach an SVG to a comment right here.  Either drag the file in from your file manager or click the link below the text box to open a file picker.

If you'd rather keep stuff private, let me know and we'll figure something out.

**Comment by lexelby** [comment]
BTW, did you get CSV generation working?  You might need to adjust the output directory in the extension's settings.

As to simulate, I think the problem was that it couldn't find your CSV file.  You'd need to enter the same directory in the simulate extension's settings.

**Comment by wwderw** [comment]
I'll post a zip with everything in it, what worked, what didn't, thoughts on other options etc and I'll just use generic shapes etc for the SVG file.

> BTW, did you get CSV generation working? You might need to adjust the output directory in the extension's settings.

I'll address this more indepth when I post, but I was able to generate a CSV from the Embroider module no problem.

I'll try to get everything posted tomorrow, day after for sure (I hope, between freelance and having a little one cutting his first 2 teeth, experimenting has taken a hit this past week).

**Comment by lexelby** [comment]
Oh teething, I totally understand.  Take your time, and thanks :)

**Comment by lexelby** [comment]
@wwderw You might want to give this version a shot: https://github.com/lexelby/inkstitch/releases/download/untagged-a75b91abcf9063b5b0b4/inkstitch--Linux-x86_64.tar.gz

It fixes a problem with the previous one where the GUI theming was messed up in the Params window.  It also fixes the spew of errors from Simulate.

Sorry if you're getting email spam from all these commits... I think I've finally got this thing tackled!

**Comment by wwderw** [comment]
Wow, wow, wow.  I'm loving this extension.

In the zip file, you'll see the 2 SVG files that I created.  The main difference between the 2 is an extra layer for a different color.  And the third is a text file that has my thoughts on the testing.

After I did the work in Inkscape, I tested the resulting raw stitch files in Wilcom's TruSizer program.
[InkStitch Testing.zip](https://github.com/lexelby/inkstitch/files/1621272/InkStitch.Testing.zip)

**Comment by wwderw** [comment]
> You might want to give this version a shot: https://github.com/lexelby/inkstitch/releases/download/untagged-a75b91abcf9063b5b0b4/inkstitch--Linux-x86_64.tar.gz

It fixes a problem with the previous one where the GUI theming was messed up in the Params window. It also fixes the spew of errors from Simulate.

Sorry if you're getting email spam from all these commits... I think I've finally got this thing tackled!

I've got it loaded up.  I'll give it a testing tomorrow.  

Thanks for all of the hard work!

**Comment by wwderw** [comment]
I sketched out a quick design that would force me to try out everything that I would normally do with in a design.

Right now, I'm getting this error
`Traceback (most recent call last):
  File "embroider.py", line 2031, in <module>
    
  File "inkex.py", line 283, in affect
  File "embroider.py", line 2011, in effect
    
  File "embroider.py", line 1663, in to_patches
    
  File "embroider.py", line 1609, in do_zigzag_underlay
    
  File "embroider.py", line 1518, in walk_paths
    
  File "site-packages/backports/functools_lru_cache.py", line 113, in wrapper
  File "embroider.py", line 1368, in flattened_beziers
    
  File "embroider.py", line 1395, in flatten_beziers_with_rungs
    
  File "site-packages/shapely/ops.py", line 465, in split
ValueError: Splitting a LineString with a GeometryCollection is not supported
[24309] Failed to execute script embroider
`
When trying to do a satin column.  The stroke width (solid stroke) is well beyond the minimum that shouldn't result in a run stitch.  This was using the latest release.

Thoughts?

**Comment by lexelby** [comment]
Awesome feedback, thank you so much!  All of your suggestions sound interesting, none of them is a "pipe dream".  Keep them coming.  If you have a chance, could you convert them to issues in this repo so that I can track them and close them as I implement them?  Some are easy enough that I can probably whip them up pretty quickly.  Others, as I think you know, will take some time, and even some discussion to fully flesh out what they should look like.

The answers to some of your questions:

==Flip==

The Flip feature is in the "Fill" tab, which really should be labelled "Manual Fill" or even "Don't use this, it's outdated".  I've considered actually getting rid of the manual fill feature altogether.

Here's the deal: initially, there was no automatic fill stitching.  If you created a blobby shape with lobes and even holes in it, the extension would break it up into sections that it could fill with rows, and then it would just haphazardly jump-stitch between them.  To get a proper design that sewed in one go without weird jumps, you'd have to break up the fill region into sections and tinker with them to adjust the stitching path and sequence.

Flip was useful because it would cause stitching to start in the upper right instead of the upper left, and in combination with rotating 180 degrees, you could start in any of the four "corners" of a shape.

Autofill does away with all of that by handling the routing of fill stitch for an entire region at a time.  What it lacks is the ability for you to specify where it should start and end, like you can do in Hatch and others.  There's rudimentary support for controlling the starting position for a fill: it knows where stitching left off from the previous object and it picks the closest point on the fill reigon's border and starts there.  But it kind of cheats, because it just does running stitch around the outer border until it gets to where _it_ wants to start. :)

Bottom line: flip is an old option that probably isn't what you want.  My question for you is, what are you trying to do that Flip didn't do for you?  Maybe you want to start at the bottom of a shape?  If so, try setting the angle to 180 degrees, for starters, but I'd also like to hear if that doesn't fulfill your needs.

==Dash/stroke issue==
I think you ran into a bug, w.r.t. having to remove the satin_column attribute.  I've had to do this before as well, but I haven't yet figured out how to reproduce the problem.  If you can reproduce it from a blank canvas, I'd love to hear how.

==Simulator speed/stitch count==
Hidden feature: you can speed up and slow down the simulation by pressing plus and minus on your keyboard (equals works the same as plus, so no need to hit shift).

> Or, if some extra functionality can be put into the simulator to include speed, player and stitch count info

Layer?  That's a great idea and sounds like a really useful feature.  Even cooler would be layer _and_ object name.  I also love the idea of displaying the current stitch and the total number of stitches, like "990 / 10501" or something.

== PDF Printout ==
This sounds really neat!  I like the idea of printing each layer separately.  That said, we're starting to run into the limitations of my expertise.  Maybe I could make use of inkscape itself to have it export things as image files... I'd have to look into it.

One thing is... are you saying you'd like to send the Simulator (or even the Embroidery layer) as it is to your customer?  I know most embroidery software renders things using actual simulated thread, whereas Inkstitch just draws plain lines... is that good enough for your customers?  The reason I ask is that I'm really not sure how I'd make pretty simulated thread imagery.

== Stop Command ==
To do this right, we'll need support from libembroidery, as you say.  But on some machines, just changing colors pauses the machine (maybe not on fancy machines though?).  So maybe you can alter the color slightly?  Even a single-digit change in red, green, or blue from one object to the next causes a COLOR instruction to be added, and on my brother SE400, that causes a pause.

== Presets ==
In linux, they're saved in `~/.config/inkstitch`, and you can move those from machine to machine freely.  Upgrading the extension in `~/.config/inkscape/extensions` doesn't blow away your presets, which I think is a good thing.

If you want to be able to bring both presets and the extension to a new system, perhaps create your own tarball from inside ~/.config, that contains both the inkstitch preset directory and all the extension files/directories?  Puppet or similar tools may help too...

== Final Thoughts ==
> I'm digging this extension.
> 
> Being able to leverage the pros of Inkscape and be able to do embroidery.  This is the final piece of actually being able to go into Linux fully.
>
> I love the fact that it's portable (all that frustration paid off) and it can easily be moved from computer to computer.
>
> I'm looking forward to future versions of this and if ever need something debugged, I'm here.

I'm so glad it's useful for you!  This is big for me, having the perspective of someone who does this for a living.  Thanks again for your contributions, and hopefully we can shape this up into an even more awesome tool.

**Comment by lexelby** [comment]
That satin error -- I think this is a case of a very poor/useless error message where it really should tell you want its problem is.  There's something about how you've formed the shapes that Inkstitch doesn't like.  Could you share your SVG so I can pinpoint the problem?  Then we can generate an Issue.

**Comment by wwderw** [comment]
> If you have a chance, could you convert them to issues in this repo so that I can track them and close them as I implement them? Some are easy enough that I can probably whip them up pretty quickly. Others, as I think you know, will take some time, and even some discussion to fully flesh out what they should look like.

Sure, I can see about generating individual "issues" for the features.  I didn't want to add them individual just in case I was off my rocker with the suggestions.  Since I'm not a coder, I really don't know what's possible or not, so I may suggest something that sounds great in theory, but not practical with implementation.  But when I have the time, I'll create those individual "issues".

>Bottom line: flip is an old option that probably isn't what you want. My question for you is, what are you trying to do that Flip didn't do for you? Maybe you want to start at the bottom of a shape? If so, try setting the angle to 180 degrees, for starters, but I'd also like to hear if that doesn't fulfill your needs.

I didn't realize it had been deprecated.

My goal is/was to try to dictate a start point to where I wanted as I could without generating that outside run stitch.

I did notice that we could swap out the stitch angles to change where it starts.  The concern there is, some objects (depending on the design itself) would visually benefit from a very specific angle, that would be the only downside there as that would force a very specific start point.

>==Dash/stroke issue==
I think you ran into a bug, w.r.t. having to remove the satin_column attribute. I've had to do this before as well, but I haven't yet figured out how to reproduce the problem. If you can reproduce it from a blank canvas, I'd love to hear how.

I'll see about replicating the object in question by itself in a different file and upload it to the respective "issue".

>==Simulator speed/stitch count==
Hidden feature: you can speed up and slow down the simulation by pressing plus and minus on your keyboard (equals works the same as plus, so no need to hit shift).

That's good to know on the speed control aspect.  I rarely use "+" and "-" except when editing audio waveforms for animation.  Simple and logical (which probably explains why I didn't think of it, as I'm not either one of those things).

>== PDF Printout ==
This sounds really neat! I like the idea of printing each layer separately. That said, we're starting to run into the limitations of my expertise. Maybe I could make use of inkscape itself to have it export things as image files... I'd have to look into it.

One thing is... are you saying you'd like to send the Simulator (or even the Embroidery layer) as it is to your customer? I know most embroidery software renders things using actual simulated thread, whereas Inkstitch just draws plain lines... is that good enough for your customers? The reason I ask is that I'm really not sure how I'd make pretty simulated thread imagery.

When I create this issue, I'll see if I can upload just a sample of how Wilcom does it in their Trusizer program.

Although, ideally it would be best to have realistic simulation for this.  I do think my customers would expect that given that they are used to that with Wilcom printouts that I send.  I could bring the CSV file into the main EmbroiderModder program and take a screen shot of it's simulated view.  Import that into a Scribus template and manually create all of this.  That could be a work around.

>== Stop Command ==
To do this right, we'll need support from libembroidery, as you say. But on some machines, just changing colors pauses the machine (maybe not on fancy machines though?). So maybe you can alter the color slightly? Even a single-digit change in red, green, or blue from one object to the next causes a COLOR instruction to be added, and on my brother SE400, that causes a pause.

For single needle machines, that's all that's needle.  With multi-needle machines, it gets more complicated to approach that, it's actually best to invoke a true stop command.

If we can get the EmbroiderModder project to get that in the lib convert module and we have the ability to view individual stitch numbers, a stop (or any other function) could actually be done in the CSV file and then that converted to a DST (more then likely).  It's just mainly getting it supported in libembroidery.

>== Presets ==
In linux, they're saved in ~/.config/inkstitch, and you can move those from machine to machine freely. Upgrading the extension in ~/.config/inkscape/extensions doesn't blow away your presets, which I think is a good thing.

If you want to be able to bring both presets and the extension to a new system, perhaps create your own tarball from inside ~/.config, that contains both the inkstitch preset directory and all the extension files/directories? Puppet or similar tools may help too...

That's good to know.  I didn't think about that spot.

I'll see about getting those issues posted when I'm able and take it from there.

Thanks again for all the hard work.

**Comment by lexelby** [comment]
> Sure, I can see about generating individual "issues" for the features. I didn't want to add them individual just in case I was off my rocker with the suggestions. Since I'm not a coder, I really don't know what's possible or not, so I may suggest something that sounds great in theory, but not practical with implementation. But when I have the time, I'll create those individual "issues".

Thanks, I appreciate it!  I'm happy to hear suggestions from a non-coder, because you have a valuable perspective that I don't share.  If you do come up with something impractical, that's fine and I'll let you know, but so far I haven't seen anything off the wall :)

> I didn't realize it had been deprecated.
> 
> My goal is/was to try to dictate a start point to where I wanted as I could without generating that outside run stitch.
> 
> I did notice that we could swap out the stitch angles to change where it starts. The concern there is, some objects (depending on the design itself) would visually benefit from a very specific angle, that would be the only downside there as that would force a very specific start point.

Yup, thought so.  Created issue https://github.com/lexelby/inkstitch/issues/20

>  Simple and logical (which probably explains why I didn't think of it, as I'm not either one of those things).

The actual explanation for why you didn't think of it is that the UI has absolutely no hint that this is possible, and it's not even in the documentation. ;)  Created issue https://github.com/lexelby/inkstitch/issues/21

> Although, ideally it would be best to have realistic simulation for this.

Yup, thought so.  I'm really not sure how to implement this... will definitely have to think on it.

>  It's just mainly getting it supported in libembroidery.

As a note, modulo my free time (which is often in very short supply...) it's definitely possible that I'd be able to write the code in libembroidery to handle this.

**Pull request merged**
