### PR TITLE
input extension for all libembroidery-supported formats

### PR DESCRIPTION
**Pull request by lexelby**
This adds an input extension that allows Inkscape to read all of the formats supported by libembroidery.  Using File -> Open or File -> Import, you can load up an embroidery design just as if it were an SVG!  The extension reads the stitches contained within and converts them into manual-stitch embroidery vectors, allowing you to make changes as needed.

I'm especially excited about how easy this was to implement.  The input extension is just *30 lines of code*!  This is thanks to all of the code reorganization as part of the Print extension.

There are a couple of things left to do, but I wanted to get this in front of you folks for testing ASAP.  Here's what's left:

* Rename the "Stitch Plan" layer.  Right now it uses the existing Stitch Plan logic to generate the SVG, but that means that if you do Embroider, it'll erase the layer (oops).
* proper HTML escaping for input INX files
  * one of the format descriptions has an & in it
* Center the design in the canvas?
  * possibly add Embroidery Origin guides?
    * the downside of this is if you use File -> Import -- it probably doesn't make sense to add more guides!
  * We could just leave it loading the design in the upper left corner, with the origin of the embroidery file at (0,0).  I haven't decided yet.

### CODE REVIEW

**Comment by X3msnake** [comment]
@lexelby Awsomeness

I'll see if I can test it tomorrow @ the makerspace.

Thanks for another goodie :D

**Comment by wwderw** [comment]
Awesome.

I think having it using the traditional file open/import is far more intuitive for this type of functionality versus using another extension to bring it in.  It just makes it seamless and gives the appearance that Inkscape is more embroidery program-ish then just going through an extension for everything.

One question, when importing in, is the rendering more visual or is it also making changes as well?  Reason why I asked, I imported some files that I know have trims in certain areas, but they are rendering as jumps.  So I don't know if it's just a visual thing or if it's like Thred and when you bring that file into Thred, it overrides those trims and makes them jumps or if it's just visual.

This is just awesome.

**Comment by lexelby** [comment]
Hmm, l'll have to give trims some thought.  I'm not actually sure what it does for them right now.

**Comment by lexelby** [comment]
Okay!  This fixes the following:

* the layer is named after the embroidery design file
  * especially useful when using File -> Import
* trims are retained
  * This also applies to the Embroider extension. If you Embroider something with trims, the stitch plan objects get "TRIM after" set.  I consider this a bug-fix.
* "Bits & Volts" -> "Bits &amp; Volts"
* Design's origin is centered in the canvas
  * The canvas is resized accordingly so that the entire design fits in the canvas.
  * If the embroidery origin is off-center in the design, then the design will appear off-center in the canvas, but the canvas will be sized to fit the full extents of the design.

At this point, I consider this feature-complete, so it's ready for final bug testing once it finishes building.

**Comment by X3msnake** [comment]
@lexelby  what's Bits & Volts?

**Comment by lexelby** [comment]
No idea.  Some random embroidery file format that libembroidery supports.

**Comment by X3msnake** [comment]
I see

Looks like it is a embroidery software 

https://www.google.pt/amp/s/softbordados.wordpress.com/2013/07/11/bits-volts-bv2000-7-11-embroidery-software/amp/

**Pull request merged**
