### PR TITLE
WIP: print through web browser

### PR DESCRIPTION
**Pull request by lexelby**
After a ton of work from all of us, here's a first pass at a printing extension.  To use, install it like normal and be sure to restart inkscape so that it recognizes the new extension.  Extensions -> Embroider -> Print should pop up a new tab in your default browser.

The extension starts a simple web server and points the web browser at it.  The web server has to stay open to serve all of the rest of the content (fonts, icons, etc), so inkscape will sit and wait.  To shut down the web server, visit http://localhost:5000/shutdown.  That will return control to inkscape.

In this first version, inkscape will then show some debugging output.  Don't worry about it, I'll get rid of it in a later version.  No need to paste it here.

Next up:

* refine the templates
  * @kaalleen has a new version with the swatches implemented entirely in SVG
  * get the page sized correctly (I shrunk it down so it would fit but I didn't pay particular attention to getting the size right)
* perhaps add a simple wxPython popup window that lets them shut down the extension
* add a button on the web page to print
* add a button on the web page to shut down/finish
* fill in values for stitch counts, number of jumps, etc

The above should get us a "minimum viable product".  I'd like to get this basic version ready and release it, and we can add in more features in later versions.  That would be things like toggling whether certain pages are printed, adding in notes, etc.

### CODE REVIEW

**Comment by X3msnake** [comment]
@lexelby @kaalleen Thanks for your great work Masters.

Where is the release for testing?

We really need a tutorial on how to compile from source ;)

**Comment by lexelby** [comment]
Okay!  I fixed the automatic browser opening.  I also added static file serving and included jquery and Barlow directly in the repo so that internet access isn't required to print.  I also added Close and Print buttons.  The Close button closes the tab and also tells the extension to exit so that inkscape resumes.

Print works great on Chrome, and it gives us something we weren't going to get with the embedded browser: an actual print preview.  I'm really starting to like using the default browser instead of packaging an embedded browser.

To tinker with the CSS, you can just go into the inkscape extensions directory, mess with the files in inkstitch/bin/print/resources, and hit reload in your browser.  I think that should work fine.  If you want to tinker with the HTML templates, you'll need to restart the extension.

**Comment by kaalleen** [comment]
I updated the template. I think there are some changes needed. When I tested it, the color swatch was all black and there was only one - although I added two colors to the svg image. So I did miss something within my update. @lexelby you should have a closer look at the gettext implementation. I did it only that far, that it wouldn't throw an error.

**Comment by kaalleen** [comment]
Oh, nevermind. The number of swatches is correct. But it is black ;) I will be looking into it.

**Comment by kaalleen** [comment]
Also we need to add color_blocks.color.fontcolor. Can you do it? Doesn't matter if it is all the same for now.

**Comment by lexelby** [comment]
The color blocks are black because the html ends up as `rgb((100,200,100))` (for example).  `color_block.color.rgb` returns a string that already has the parentheses.  Sorry about that!

I can do font_color, no problem.

**Comment by lexelby** [comment]
Okay, there's the color picking for the swatch font color.

For the Close and Print buttons at the top, I wonder, can we turn that into a little bar that stays at the top even when they scroll down?  We can label it, something like "Ink/Stitch Print Preview" or something, and add more buttons up there later as we add more features.  I'd do it, but that's really beyond my meager CSS skills :)

**Comment by lexelby** [comment]
Yay, thank you!

Nice one with the beforeunload. I think the code get a little jumbled though?

```
window.addEventListener('beforeunload', setTimeout(function() { 

$.post('/shutdown', {})

}), 1000);

```


Should the setTimeout be inside the function?

**Comment by kaalleen** [comment]
Yes, beforunload looks a bit overdone with a timeout function set. But I actually got errors with both, firefox and chromium, if I didn't. Maybe more testing is needed?

**Comment by lexelby** [comment]
Oh, I didn't mean it looked overdone.  It looked to me like the setTimeout call was misplaced, but maybe I misunderstood?

In any case, it didn't work until I removed it, and now it seems to work fine.  I didn't check the console though, and I haven't yet tried it in Firefox...

**Comment by kaalleen** [comment]
Not sure, but maybe we shouldn't use beforeunload at all. It might cause problems. The downside of using it is, that it cannot distinguish between closing and leaving the website - maybe to look at an other website or document to come back later. The preview will seem to be working, while the server is already closed?!

**Comment by lexelby** [comment]
Wow, I really love what you've done!  The top bar looks so awesome and the settings pane is great.  I don't have anything to put in there yet, but I'm sure we'll have stuff soon. :)

> Not sure, but maybe we shouldn't use beforeunload at all. It might cause problems. The downside of using it is, that it cannot distinguish between closing and leaving the website - maybe to look at an other website or document to come back later. The preview will seem to be working, while the server is already closed?!

Well, there are a couple of things to consider here.  First of all, just switching to another tab won't trigger the `beforeunload`.  There aren't any links in the print preview (yet) so there's no reason that they'll navigate to a new page.  If we have any links, we can set the target to `_blank` to open a new tab.

Another thing is, it's actually not too terrible if the server is closed but the print preview is still open.  They can still print from it just fine, because the SVG content is embedded in the HTML and it's already loaded.  The only thing they wouldn't be able to do would be to have settings saved back into the SVG.  If they do change any settings like that, we can pop up a warning or put something in the header that says that saving will no longer work because the connection was lost.

**Comment by lexelby** [comment]
@wwderw Do we actually want the "client signature" box on each color block page, or just a signature sheet at the end?

**Comment by wwderw** [comment]
> @wwderw Do we actually want the "client signature" box on each color block page, or just a signature sheet at the end?

I would do it on the approval sheet only (the one with the simulated view of the entire design) as that would also indicate approval of the colors used as well.

**Comment by lexelby** [comment]
> I would do it on the approval sheet only (the one with the simulated view of the entire design) as that would also indicate approval of the colors used as well.
Ah, I wondered if it might be something like that.  That sounds right, but it's going to require some changes to the design.  Not my forte... @kaalleen or @X3msnake?

**Comment by lexelby** [comment]
I implemented various things like number of trims, stops, stitches, etc.  I changed things around in the top header, adding "unique colors" and "color blocks" to make it clear if colors have been repeated.

I set the title and client as "contenteditable" so that one can at least modify them before printing.  The modifications won't "stick" yet because there's no javascript to send the changes back to Ink/Stitch.

We're really close to a first version that we can merge in!  I think it makes the most sense to leave the more complicated javascript stuff for a later pull request.  This one already has a ton of changes and we really ought to pick a stopping point.

**Comment by kaalleen** [comment]
I did some changes to the editable fields. I thought it might not be convenient to delete the underscores when entering a name. So I set a placeholder instead. I also added a little jquery to have the changes take effect on all pages. Maybe we can also grap the value from there to send it back to python?

About the other changes... I could do, but I want to wait if maybe @X3msnake wants to work on it, since it is your design?

**Comment by kaalleen** [comment]
Oh, an other thing I noticed: when I run the print option in Ink/Stitch while Firefox is already running, I will see printers. But when Firefox is started by Ink/Stitch, there won't be any printers. Chromium doesn't have this issue.

**Comment by lexelby** [comment]
Ooh, love the placeholders!  I riffed on that idea a bit and made them faded out.  What do you think?

> Oh, an other thing I noticed: when I run the print option in Ink/Stitch while Firefox is already running, I will see printers. But when Firefox is started by Ink/Stitch, there won't be any printers. Chromium doesn't have this issue.

Wow, I have no idea what to make of that.  It almost has to be some kind of firefox bug...

**Comment by lexelby** [comment]
I thought better of `beforeunload` and got rid of it.  Now, javascript makes a request to `/ping` once per second, and if the extension doesn't hear anything for 4 seconds, it shuts down automatically.  This way, even if the user hits the reload button, the extension doesn't shut down.  This is especially convenient for us when we tinker with the CSS!  It also means that closing an old print preview tab doesn't accidentally shut the extension down.

If the javascript's request to `/ping` fails, it displays a little warning message in the upper right, "lost connection to Ink/Stitch".  Probably an unlikely event, but having some kind of feedback is useful.

**Comment by kaalleen** [comment]
Nice updates, like them both! I am really happy about removing beforeunload. I wasn't really satisfied with it, but now it's working great!

The contenteditable fields will add an other span element to the dom when hitting return or enter. This is unwanted behavior for us. I will add a line of jquery to prevent it.

There is an other thing, I wanted to ask. It's about the paper size. It won't be difficult to set up the CSS to change to the desired size, maybe with an additional class (which we could also add and remove through the settings with jquery). The question is, how do we want to define the standard size. Do you think, you could create a python variable depending on language/country settings saying A4 or letter is the standard size? I think it would be inconvenient to have to change to A4 manually every time you want to print to PDF in an A4 using country.

**Comment by kaalleen** [comment]
@X3msnake I couldn't wait ;) But if you have a better idea, go ahead and change it to your taste. I thought, it wouldn't be the best idea to have the signature at the end of the color swatches, since they are very small if there are a lot of colors. So I placed it below.

I was thinking though, if it is a good idea to have the color block extend to full width on the detail pages. What do you think @wwderw ? Would it be ok, because most people won't even actually print it out - or is it a waste of ink? Also i was wondering, how many colors should be at least visible and what should we do, if someone has even more colors in the design? Should we change the last visible block to an infobox, to inform that there are some colors not shown on the overview page?

@lexelby I added a function to change the paper size. This is for testing only, you can remove it - or make it better if you like ;) I think it is important to have A4 as an option though. Also I know, you want to be ready for a first release soon, so I won't add any new code up from now - no worries ;)

**Comment by lexelby** [comment]
Looking great!

I can't for the _life_ of me figure out how to get the default paper size for the current locale.  The next best thing is to store their choice in a separate settings file -- much like I already do for presets in Params.  Let's add that in a later PR.

What's left for a minimum viable release?

* make color names and thread descriptions editable with a placeholder
* Ink/Stitch icon (coming soon)

Anything else?

I think you're right that having the color swatch be the full width in the color detail page is probably too much.  How about just have it be a square and put the text next to it? 

So close!

**Comment by lexelby** [comment]
Oh, I should have said: let's leave your paper size selector in.  Seems important for a minimum viable release.

**Comment by wwderw** [comment]
> I was thinking though, if it is a good idea to have the color block extend to full width on the detail pages. What do you think @wwderw ? Would it be ok, because most people won't even actually print it out - or is it a waste of ink? Also i was wondering, how many colors should be at least visible and what should we do, if someone has even more colors in the design? Should we change the last visible block to an infobox, to inform that there are some colors not shown on the overview page?

What I'm typing here may change when I play around with the official dev copy, but for the overview page, we may want to just mention how many color changes that there are (total changes, doesn't matter if it's a unique change or not).

For the detailed, we want to have it all.  I personally would scale the individual box(s) down to be able to fit the info that we want on there as more colors are being used.  Designs with blends (due to the special production needs) will have a lot, and I do mean a lot, of color changes.  The one that I had posted in another thread had 43 color changes, but only 12 unique colors.  All those color changes need to be able to be shown to the operator.

I can't speak for everyone, but I don't actually physically print out, I use Cups and just send it to PDF.  I can't speak the same for my customers, so it would be better to assume that they are going to be printed out then not.  The more economical we can be, the better.

Again, I may change when I'm able to play with the official dev version and see.  I've been holding off to make sure it's all new when I get to look at it.

**Comment by lexelby** [comment]
Augh!  It turns out that when a script runs `window.print()`, all javascript activity is stopped while the print screen is open.  That means that the Javascript will lose contact with the extension and the extension will exit.  This happens in Chrome, Firefox, and Vivaldi (a chrome-based browser).

In firefox and chrome, if I do File -> Print or Ctrl-P, javascript doesn't get paused.  In Vivaldi, File -> Print and Ctrl-P do nothing(!).

I'm not really sure how to handle this.  I like having a Print button there, but maybe we should get rid of it and tell the user to do File -> Print?  And I guess we can just say Vivaldi's got a bug and ignore it?

Another option is that the javascript could tell the backend that it's about to print and tell it when it finishes, and that could suspend the timer for closing the extension.

Thoughts?

**Comment by kaalleen** [comment]
@lexelby Hm, I like the print button too, although it's not really necessary, it somehow seems nice to have. I think I'd like the last option with the timer. Do what you think is best!

@wwderw Wow, that is really a lot! A lot of pages too, since we have one color per page. I think we should leave it as is and when you have the chance to look at it, you can say, how it could be done better ;) Possibly we want to add an other print layout for operators, to have a table-like overview without running out of space for the color information? Well, I better wait thinking about it, until we have the minimum release.

**Comment by wwderw** [comment]
> Possibly we want to add an other print layout for operators, to have a table-like overview without running out of space for the color information?

I'm thinking something minimalist as well.  Something that is just color blocks in the correct sequence with core info is needed (like stop info etc).

Or another another option is make the single color pictures, more thumbnail in size, so we can fit more then just 1 to a page.  I think the one page that needs to be as close to 1:1 is the entire design page.  I think we have more room to wiggle with sizes on the others.

But like you said, wait until we have a minimum release and see what direction would be best.

**Comment by kaalleen** [comment]
@wwderw I thought we could better discuss the issue, if there is already something to see. So I created an operator view. The preview-icons might be a bit too small, but at least we will have 13 colors on one page instead of one - still you might want them bigger though. Curious what you will think about it.

@lexelby I added settings for the layout choices. They are very simple with a toggle function. As with the paper size, we might want to check which setting is set before - otherwise it might have issues after reload. But at least it's working. Next thing I noticed that the page numbers will vary with different layout settings. I added a jquery function to solve this part.

Well, now I will really stop ;) Just thought this part might be important to have already now.

**Comment by wwderw** [comment]
> I thought we could better discuss the issue, if there is already something to see. So I created an operator view. The preview-icons might be a bit too small, but at least we will have 13 colors on one page instead of one - still you might want them bigger though. Curious what you will think about it.

I can only speak for myself, but that thumbnail view is actually pretty close to what I had in mind.  For me personally, that'll work.

**Comment by lexelby** [comment]
Amazing!  Thank you, this really helps round out the printout.

> Well, now I will really stop ;) Just thought this part might be important to have already now.

Eh, in for a penny, in for a pound. ;)  I was actually going to suggest we get the tabular thread list in before merging since I feel that it's so important.  We'll get things stabilized soon.

That reminds me: before we can fully merge this version, it would be good if all of you could also regression-test all of the other aspects of Ink/Stitch that aren't related to printing.  I reorganized large sections of the code in order to make the print functionality easier to implement, and it's entirely possible that I've introduced small bugs here and there.  If you have any test designs you've made before, now would be a good time to run them through and make sure that the stitch plan is generated properly, simulate works as expected, etc.

**Comment by wwderw** [comment]
Inserting a stop code gives the first message in the txt file and after applying the stop code, the second message is given when trying to "print" with the stop code.

[Stop Error.txt](https://github.com/lexelby/inkstitch/files/1845837/Stop.Error.txt)

Simulate gives me this error msg:

[Simulate Error.txt](https://github.com/lexelby/inkstitch/files/1845838/Simulate.Error.txt)

I think the stop code is what is responsible for everything in the error message.


I did not observe the jump stitch error in the same design as before (my fringe design) like what was talked about in #128, however, I did still have the exploding PES file.  It seems to reliably happen with this file in the PES format.

Everything thing else seemed to work right.  Simulate did fine when I didn't have a stop, but it didn't work as expected when I did have a stop, so I'm thinking stop is the big concern some of the regressions.

The printout itself is looking way cool for a first release.  Just a couple of things that I noticed, but otherwise, it's looking killer.  I do think that the first run at thumbnail size for the operator view is spot on.  Again, this is just my thinking, but I think it's spot on.

Awesome job everyone!

**Comment by X3msnake** [comment]
@lexelby @kaalleen 

Very good job Masters it is looking great :D :+1:

@kaalleen Great that you joined the project your skills are way better than mine at this webstuff thank you for bringging the design together :D 

@lexelby I downloaded what i hope is the latest version and the logo comes out as a missing picture is this the latest or am I doing something wrong?

Also there is a misalignemt in my browser view and no stitching is showing up

image

**Comment by kaalleen** [comment]
@X3msnake The logo is not included yet ;)
The reason why you see no svg picture might be the scaling. The image is as big as your working space in inkscape. You could try scaling the inkscape document size to the size of your design, or move your design to the top left corner. I am quiet sure, that you will see something then.  Well, that is a temporary solution.

@lexelby do you want to solve the scaling through the svg output - or is it something we are going to do with jquery and css? If it is the last option, I could put my hands on it - if you like.

I forgot yesterday to mention, that I added a string saying 'thread company name' (or something like that) to the thumbnail view. Where do we get this information from? Is it an input from the user through the website or do we get this value from the name of the color palette that was used in inkscape? Or do we not need it - because it is somehow missing within the other templates?!

**Comment by wwderw** [comment]
> Is it an input from the user through the website or do we get this value from the name of the color palette that was used in inkscape?

Company name and the actual thread color used (or however, it's named in the palette) should come through the color palette being used **if** it's a thread palette and not just one of the generic included palettes.

Also, I noticed that when using white thread, it doesn't show up obviously due to the white background.  This tends to be an issue with all programs that I've had experience with and having this functionality.  Any thoughts as a way around this or just nature of the beast (I'm thinking this as it seems to apply to all software that I'm familiar with).

**Comment by lexelby** [comment]
@wwderw @X3msnake Thanks for the bug reports! I'll get those fixed up soon.

@kaalleen My hope was to handle scaling and panning by letting the user drag the previews around and zoom in/out (perhaps with scroll wheel?).  Seems like a fairly large chunk of code, but we can go ahead and do it if folks think that's necessary for a minimum viable release.  If we can push that off to a later PR though, I'd prefer that.

Thread name and manufacturer info is supposed to come from the palette in Inkscape.  I hadn't gotten to implementing that, so as a stopgap I was just going to make thread names editable in the print preview for this first version.

@wwderw Regarding white thread, that's easily dealt with.  I'll put a fix in soon.  You can see if you try Simulate that I've already written code to choose a color that is visible against a white background.  I'm kind of surprised that this is a common failure mode across all embroidery programs!  It's very easy to fix, code-wise.  I guess this will be a way that Ink/Stitch can lead the pack :D

**Comment by wwderw** [comment]
>  that this is a common failure mode across all embroidery programs! 

This is the best one that I've seen here out of the commercial ones that I have.  Now, bare in mind, this particular program is not the latest version, it's one generation back, but for my purposes, it's fine.

pure white

**Comment by kaalleen** [comment]
@lexelby We might make use of https://jqueryui.com/resizable/ and http://api.jqueryui.com/draggable/ ?
What do you think? I really don't mind having it in an other release. But a simple resize to fit the preview svg into the box would be really a good idea, because otherwise people will think, that there is no image at all. If you don't mind, I can put that in.

**Comment by lexelby** [comment]
Definitely, using those libraries is fine with me so long as their licenses are compatible.  I like your idea of just putting in a simple resize for now, go for it.

**Comment by lexelby** [comment]
Okay!  Fixes in for:

* print after embroider
  * and embroider after embroider
* "STOP after" crash
* white thread

For the white thread fix, I actually made it visible in the Stitch Plan layer when you run Embroider, too.  I also added a thin grey border around the color swatches on the printout.  It's almost invisible unless you're using white thread, at which point it makes it obvious that the color swatch is white.

**Comment by wwderw** [comment]
That seems to have fixed the bugs that I noticed.

The only thing is that the Ink/Stitch logo in Operator Detailed View, the bottom part hits a portion of the top row.

logo


Other then that, it appears from my testing to be good to go.

I'm really liking this.  This is looking awesome.

**Comment by X3msnake** [comment]
@kaalleen @lexelby 

Awsome it is looking very professional and clean.

image

Same logo issue as @wwderw here and also the color blocks are not mathing the stitchout box

image

image


Also it would be better if the Stitching SVG was centered on the origin guides or at least centered on the page :)


@lexelby can you please partially fix #125 in this release so that the satin follow the set size instead of defaulting the value to pixels

**Comment by kaalleen** [comment]
@lexelby I like the fix for the white color, it's simple and nice!
I added a resize function. Hope it will do it's job for now ;)

@X3msnake @wwderw Thanks for reporting. I fixed the logo size for the detailed operator layout. Surprised it did fit within the others :)

@wwderw I set the default layouts to be the ones for the operator. It seemed like it's what you would think is best?

@X3msnake I thought I did fix the mismatch of svg and color swatches long ago, obviously I didn't. Thanks for the reminder ;) Also the layout will now resize to fit into the box. It will only be centered, if it was centered inside the inkscape document. You will now be able to see the whole design though.

**Comment by X3msnake** [comment]
@kaalleen it's awsome :)

**Comment by wwderw** [comment]
I concur with @X3msnake in that it is "awesome".

**Comment by lexelby** [comment]
@X3msnake okay, there's your #125 fix, I think.  Give it a go :)

**Comment by lexelby** [comment]
@kaalleen Love the scaling!  I tweaked it just a bit to make sure that it centers the SVG even if it was already small enough to fit in the print area.

**Comment by X3msnake** [comment]
@lexelby hurray :)

Now all we are missing is the stitch as is and ability to import stitch files to have all the Essential functionalities :D

**Comment by X3msnake** [comment]
image

@lexelby it is working
Thanks for the fix :)

**Comment by X3msnake** [comment]
I give it a go on my side

I believe we are ready for a merge. Thank you both for all the awsomness work put into this, it really looks and feel great :)

**Comment by lexelby** [comment]
I thought about it and decided that we really need a way for the user to close the extension if it gets stuck.  For example, I hit the print button and was in Chrome's print preview window, and I accidentally closed the entire browser.  Since the javascript had told the extension that it was printing, the extension was no longer expecting pings, and so it never noticed that the entire browser was closed.  I had to kill the script myself at the command line.  Not a good user experience.

Now the extension pops up a little message box that tells the user that a browser tab has been opened.  It has a close button that they can use to exit the extension if they get stuck.

At this point, I think we're pretty much done!  I'm going to do some last testing, and if everything looks good, I'll merge it and tag a new release.  Then you can start a branch with those additional features, @kaalleen :D

**Comment by lexelby** [comment]
I found a couple of bugs and fixed them, and I'm gonna call it a night.  Could someone grab the latest from https://github.com/lexelby/inkstitch/releases/tag/dev-build-print-pdf once it finishes building and give it a whirl?

**Comment by kaalleen** [comment]
Nice work! Now everybody will be able to close the print preview any time. Although I sometimes seem to accidentally close the preview if the pop up appears after the browser window has opened - hope it's just me ;)

I made the color name editable in the client detailedview too. Somehow it felt right to do that. If someone misspelled the name and sees it in the client detailedview, it'd be nice not to have to go back to operator detailedview. But it is of course more comfortable to edit it within the operators layout in the first place.

I also set the loop index as po nr in detailed view? I am not sure, but I think this was the intention of this field?!? If not, please correct me.

I didn't run into bugs while testing. I think we are good to go for a first release? :) :)

**Comment by X3msnake** [comment]
@lexelby

Can you hide the deprecated update params #93 from the menu for this release?

**Comment by wwderw** [comment]
Only thing that I have found that we seem to have a regression with the lighter thread colors not showing up in the thumbnail view.

Otherwise everything is looking good.

thumbnail view

**Comment by kaalleen** [comment]
The idea wasn't actually mine, I only made it available in more places. But it's good you are saying this, so we should think about leaving the color name editable, even if we get the values through python delivered.

> Only thing that I have found that we seem to have a regression with the lighter thread colors not showing up in the thumbnail view.

Is it also not visible within the print out pdf?

**Comment by wwderw** [comment]
> The idea wasn't actually mine, I only made it available in more places. But it's good you are saying this, so we should think about leaving the color name editable, even if we get the values through python delivered.

Either that or add a box for notations.  That way it can be added into the notation's box as an alternative suggestion for some designs (I'm thinking more about stock design creation, particularly Halloween when it comes to glow in the dark thread).

You know, maybe it might be a good idea for a future release to have notations in the operator view as well.  I was thinking for some areas, particularly small fonts and/or very fine detail to add in a notation about perhaps running the machine slower and/or using a thinner needle, lighter weight thread etc.

> Is it also not visible within the print out pdf?

I didn't even think of that.  Duuuuhhhhh.

That worked.  That's what matters most as the PDF itself is what's going with the stitch file.

I say we are good for a 1st release.

Awesome job everyone.  I'm getting really excited about this release.

**Comment by kaalleen** [comment]
Ok good, glad it works ;)
If you are editing the color names, you might wish, you could see the icons better. In that case you should try to zoom (Ctrl + Scroll) and I think you will be able to see the icons as well. Not perfect, but I wouldn't know what to do about it.

**Comment by lexelby** [comment]
@wwderw, I bet the thumbnail is so small that the light thread color isn't visible just due to the scaling.  Perhaps we'll add an option later on to make the thumbnails bigger.

**Comment by wwderw** [comment]
Scaling it while in Firefox solved it for the browser view.

No worries here anymore.

**Comment by kaalleen** [comment]
I like the idea... We could have a bigger view of the thumbnails on mouseover, so nobody will be blind for the little parts and can have a closer look.

**Comment by lexelby** [comment]
I _think_ "po.nr" is "purchase order number".  I'll adjust accordingly.

**Comment by lexelby** [comment]
I couldn't stand having a printout with "CLIENT:" if the user doesn't actually want to have a client name, so I made it disappear from the printout if it's empty.  I was really trying to wait for version 2 to implement that, but I just couldn't take it anymore ;)

Okay, I'm done now.  I swear.

**Pull request merged**
