### PR TITLE
Fix simulate

### LINKED ISSUE #37: Simulation to Work with Stitch Formats?
Right now, the Simulate version of the extension only seems to work with the CSV format.

Since the addition of libembroidery convert directly to the extension, I would imagine the CSV format in most instances (other then for testing/debugging of functions in stitch files) would be skipped in place for machine files.

Is it possible to have Simulate run a simulation of say a DST, PES file etc?

### PR DESCRIPTION
**Pull request by lexelby**
fixes #37 

This one kind of grew in the telling.  #37 was a theoretically simple bug, but in reality, the code necessary to fix it was the straw that broke the camel's back, and I had to do a fair bit of (much needed) code reorganization.  Mostly the reorganization was just under the hood, but there was one user-facing change around the Embroider extension's settings window.

Way back in the day, the only way to control things like the stitch length or satin density was through global options specified in the extension settings.  We've long since moved to per-object params, but for backward compatibility, ink/stitch defaulted to the command-line arguments.
 
That means that it was possible to get different stitch results from the same SVG file if you changed the extension's settings.  For that reason, I never touched mine.  I didn't intend for my users to use those extension-level settings at all, and I've planned to remove those settings for awhile now.
    
At this point, the extension settings just getting in the way of implementing more features, so I'm getting rid of them and moving the defaults into the parameters system.  I've still left things like the output format and the collapse length (although I'm considering moving that one too).

--------------------------------------

All that said, please do test this version to make sure I didn't break anything.  **When you install this version, restart Inkscape.**  Otherwise you'll get an error about "invalid command-line parameter" or somesuch, because Inkscape will still be using the old extension definition file (`embroider.inx`).

As far as "actual" changes, this version fixes simulate for all formats.  Simulation now also properly obeys TRIMs.

cc @wwderw -- testing would be greatly appreciated

### CODE REVIEW

**Comment by lexelby** [comment]
Oh, I also changed the build system (again).  Now, whenever I create or update a pull request, Travis will build inkstitch and create just one release, like this one: https://github.com/lexelby/inkstitch/releases/tag/dev-build-fix-simulate

If I push updates to this pull request, it'll just update that same release, so the releases page won't be cluttered by a bunch of development builds.  Note that the "released this ___ minutes ago" won't update, so you'll need to pay attention to the timestamp in the description, "built on ____".

**Comment by wwderw** [comment]
Satin Column seems to have regressed.

Even though the simulation renders both run and satin stitches, when go to use Embroider, it only renders the run stitches and even though both sides were combined, it is rendering them as separate objects.

simulate

I also noticed that parameters already had "defaults" applied.  Was that on purpose?  I'm just used to their being blanks, so I didn't know if this was on purpose or not.

I really like the simplified Embroider part.  Eliminates the confusion if going through all the Params and then only to have more right before doing the stitch file.

**Comment by lexelby** [comment]
Thanks for letting me know about the satin regression.  I'll check it out later today or tomorrow.

And yes, it's intentional that the defaults are now applied. If that's undesirable from a usability perspective, do let me know.  I pulled in all the defaults from the extension settings window into inkstitch proper, and I figured I should also show them in the UI so there weren't any surprises.

**Comment by lexelby** [comment]
> Even though the simulation renders both run and satin stitches, when go to use Embroider, it only renders the run stitches and even though both sides were combined, it is rendering them as separate objects.

Hmm, I'm having a hard time reproducing this.  The thing where it's rendering both run and satin in simulate is #32, but I think you knew that.  Even when it does that, if I hit Apply and then run Embroider, I only get the satin.

Can you share your SVG file here?

**Comment by wwderw** [comment]
Stupid me, I didn't keep the SVG file, which means squat as can't replicate it. 

Some of it could have been my doing it too late at night and I just foobar mentally.

> And yes, it's intentional that the defaults are now applied. If that's undesirable from a usability perspective, do let me know. 

Not at all.  Most programs actually already have defaults.  It's easy enough to change if needed, I just wanted to make sure that it was intended, since it had been blank before.

**Comment by lexelby** [comment]
> Stupid me, I didn't keep the SVG file, which means squat as can't replicate it.
>
> Some of it could have been my doing it too late at night and I just foobar mentally.

Easy mistake to make... perhaps you slipped and hit cancel instead of apply?  That would give the results you described, I think.  In any case, let's keep an eye out in case there is a sneaky regression here.

I realized a nifty side-effect of my fix for Simulate: you can now do Embroider and then run Simulate on the resulting stitch plan.  Might save a step for certain workflows, and at the very least it "just makes sense" from a user perspective.

**Pull request merged**
